### ISSUE TITLE
IllegalStateException: Asynchronous entity add!

### ISSUE THREAD

**Issue by bog500** [CodeLanx/PlayTime#60]
I get this error sometimes

[20:54:19] [pool-7-thread-10/WARN]: Unknown CommandBlock failed to handle command
java.lang.IllegalStateException: Asynchronous entity add!
    at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.World.addEntity(World.java:991) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.World.addEntity(World.java:987) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:630) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:620) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.EntityHuman.drop(EntityHuman.java:558) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at net.minecraft.server.v1_8_R3.CommandGive.execute(SourceFile:72) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:108) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:576) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
    at com.rogue.playtime.callable.ConsoleCommandCallable.call(ConsoleCommandCallable.java:37) [Playtime.jar:?]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_60]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]

**Comment by 1Rogue** [comment]
This is not a fault of Playtime, Playtime has nothing to do with entities.

**Comment by bog500** [comment]
well this error still only happens after com.rogue.playtime.callable.ConsoleCommandCallable.call it never happens otherwise

**Comment by bog500** [comment]
it happens when playtime execute a give command with the following events.yml

  exampletwo:
    type: onlinetime
    time: 120
    at-login: false
    repeat: true
    commands:
    - 'msg %u Here''s some food for being online so much!'
    - 'give %u cooked_beef 1'

**Comment by 1Rogue** [comment]
Might be a fault when attempting to add an item to a player with a full inventory, causing an item drop.

**Comment by Pryzinho** [comment]
é só usar sync
